worker_processes auto;
#Let NGINX automatically set the number of worker processes based on available CPU cores.
events{
    worker_connections 1024;
}
#Each worker can handle up to 1024 simultaneous connections. Fine for a small project.
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    #Include the standard MIME types file so NGINX knows how to serve different file types (css, js, images etc).
    #default_type is a fallback for unknown file types.
    server {
        listen 443 ssl;
        listen [::]:443 ssl;
    
    #Listen on port 443 with SSL, on both IPv4 and IPv6. This is the only listen directive
        server_name jpflegha.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_session_timeout 10m;
        ssl_session_cache shared:SSL:10m;
        #Cache SSL sessions for 10 minutes to avoid re-doing the full TLS handshake on every request. Improves performance slightly.
        root /var/www/html;
        index index.php index.html;
        #Set the document root to where WordPress files are. index.php first because WordPress uses it as its entry point.
        location /{
            try_files $uri $uri/ /index.php?$args;
        }
        #Standard WordPress permalink handling. Try to serve the file directly, then as a directory, then fall back to index.
        #php with the query string. Without this, WordPress pages other than the homepage return 404.
        location ~\.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location ~ /\.ht{
            deny all;
            #Block access to .htaccess and other hidden files starting with .ht. A basic security measure.
        }
    }
}