[www]
#Name of the pool. Must match what NGINX references in its fastcgi config.
user = www-data
group = www-data
listen = 0.0.0.0:9000
#Tell php-fpm to listen on port 9000 on all interfaces, not just localhost. 
#This is what lets NGINX (in a different container) reach it through the Docker network.
listen.owner = www-data
listen.goup = www-data
#Set ownership of the socket/port listener to www-data.
pm = dynamic
pm.max_children = 5
pm.start_server = 2
pm.min_spare-server = 1
pm.max_spar-server = 3 
#dynamic → auto scaling workers
#max_children → hard limit (most important setting)
#start_servers → initial workers
#min_spare_servers → minimum idle workers
#max_spare_servers → maximum idle workers
clear-env = no
#it tells php-fpm not to clear environment variables when spawning workers. 
#Without this, your env vars (like database credentials) won't be visible to WordPress.
